#!/bin/bash -eux
if [ -n "${SSH_KEY:-}" ]; then
  dpkg-reconfigure openssh-server
  sed -i \
    -e 's/^#PasswordAuthentication yes$/PasswordAuthentication no/g' \
    -e 's/^PermitRootLogin without-password$/PermitRootLogin no/g' \
    /etc/ssh/sshd_config
  if [[ $(ls /etc/ssh-keys/ssh_host_*) ]]; then
    echo "Already initialized."
  else
    echo "Initializing ssh-keys folder..."
    cp /etc/ssh/ssh_host_* /etc/ssh-keys
  fi
  chmod 400 /etc/ssh-keys/ssh_host_*
  sed -i 's|/ssh/|/ssh-keys/|' /etc/ssh/sshd_config
  sed -i '/^#HostKey/s/^#//' /etc/ssh/sshd_config
  sed -e "s#SSH_KEY#${SSH_KEY}#g" /home/borg/authorized_keys.sample > /home/borg/.ssh/authorized_keys
  chown borg:borg /home/borg/.ssh/authorized_keys
  exec /usr/sbin/sshd -D
else
  echo "You need to give an SSH_KEY env variable"
  quit
fi
