#!/bin/bash

mkdir -p dist/

check_and_copy () {
    echo "--- EXE $2 -----------------------------------------------"
    vagrant ssh $1 -c "/vagrant/borg/borg.exe -V"
    vagrant scp $1:/vagrant/borg/borg.exe   dist/$2
    echo "--- DIR $2 -----------------------------------------------"
    vagrant ssh $1 -c "/vagrant/borg/borg-dir/borg.exe -V"
    vagrant scp $1:/vagrant/borg/borg.tgz   dist/$2.tgz
    echo ""
}

check_and_copy bullseye  borg-linux-glibc231-x86_64
check_and_copy bookworm  borg-linux-glibc236-x86_64
check_and_copy trixie    borg-linux-glibc241-x86_64

check_and_copy freebsd14 borg-freebsd14-x86_64
