#!/bin/bash

pacman -S --needed --noconfirm mingw-w64-ucrt-x86_64-{toolchain,pkgconf,zstd,lz4,xxhash,openssl,python,cython,python-setuptools,python-wheel,python-packaging,python-pip}
pip install pyinstaller
