#!/bin/bash

R=$1

if [ "$R" = "" ]; then
    echo "Usage: upload-pypi 1.2.3 [test]"
    exit
fi

if [ "$2" = "test" ]; then
    export TWINE_REPOSITORY=testpypi
else
    export TWINE_REPOSITORY=pypi
fi

D=dist/borgbackup-$R.tar.gz

twine upload $D
