# This is a python package

NS_CHUNK = 0
NS_ARCHIVE_METADATA = 1
NS_ARCHIVE_CHUNKS = 2
NS_ARCHIVE_ITEMS = 3

PACKET_ENCRYPT_READ   = 2 ** 7
PACKET_ENCRYPT_CREATE = 2 ** 6
PACKET_CHUNK            = 1 | PACKET_ENCRYPT_READ
PACKET_ARCHIVE_METADATA = 2 | PACKET_ENCRYPT_READ
PACKET_ARCHIVE_ITEMS    = 3 | PACKET_ENCRYPT_READ
PACKET_ARCHIVE_CHUNKS   = 1 | PACKET_ENCRYPT_CREATE

