# https://black.readthedocs.io/en/stable/integrations/github_actions.html#usage
# See also what we use locally in requirements.d/codestyle.txt — this should be the same version here.

name: Lint

on:
  push:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/black.yaml'
  pull_request:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/black.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: psf/black@35ea67920b7f6ac8e09be1c47278752b1e827f76  # 26.3.0
        with:
            version: "~= 24.0"
